check required secrets

diff --git a/.github/workflows/lempworkflow.yml b/.github/workflows/lempworkflow.yml
--- a/.github/workflows/lempworkflow.yml
+++ b/.github/workflows/lempworkflow.yml
@@ -19,14 +19,16 @@ jobs:
 
          for var in S_DOMAIN S_PUBLIC_IP S_CF_API S_CF_ZONE_ID SSH_PRIVATE_KEY SSH_USER SSH_PORT \
          S_DB_ENDPOINT S_DB_NAME S_DB_PASSWORD S_DB_USER S_EMAIL; do
-         if [[ -z "${!var}" ]]; then
-         echo "Missing required secret: $var" >&2
-         missing_secrets=1
-         fi
+          if [[ -z "${!var}" ]]; then
+          echo "Missing required secret: $var" >&2
+          missing_secrets=1
+          fi
          done
 
          if [[ $missing_secrets -ne 0 ]]; then
-         echo -e "\e[31mOne or more required secrets Missing\e[0m"
+          echo -e "\e[31mOne or more required secrets are missing\e[0m"
+          exit 1
+         fi
 
       - name: Set Cloudflare Environment Variables
         env:
