Terraform validate step added to job run

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -38,6 +38,22 @@ jobs:
         with:
           terraform_version: 1.5.5
 
+      - name: Terraform Validate
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+        run: |
+          echo "Running Terraform validate..."
+          terraform validate
+          # Check if validate command was successful (exit code 0)
+          if [ $? -ne 0 ]; then
+            echo -e "\e[31m[ERROR] Terraform configuration is invalid.\e[0m"
+            exit 1
+          else
+            echo -e "\e[32m[PASS] Terraform configuration is valid.\e[0m"
+          fi
+
       - name: Initialize Terraform
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -60,6 +76,3 @@ jobs:
           AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
           TF_VAR_key_name: ${{ secrets.AWS_KEY_NAME }}
         run: terraform apply -auto-approve tfplan
-
-
-        
