workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -58,8 +58,8 @@ jobs:
         echo "Checking key permissions..."
         ls -l private_key
     
-        echo "Testing SSH connection to ${{ secrets.S_PUBLIC_IP }} as ${{ secrets.SSH_USERNAME }} on port ${{ secrets.SSH_PORT }}..."
-        ssh -vvv -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }} "echo 'SSH Connection Successful'"
+        echo "Testing SSH connection to ${{ secrets.S_PUBLIC_IP }} as ${{ secrets.SSH_USER }} on port ${{ secrets.SSH_PORT }}..."
+        ssh -vvv -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.S_PUBLIC_IP }} "echo 'SSH Connection Successful'"
 
     # Edit Cloudflare and other variables in Bash Scripts
     - name: Edit CF Variables
@@ -87,47 +87,47 @@ jobs:
     - name: Copy files to VM
       run: |
         echo "Copying files to VM..."
-        scp -r -i private_key -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} "${PWD}/" ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }}:/opt/script/
+        scp -r -i private_key -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} "${PWD}/" ${{ secrets.SSH_USER }}@${{ secrets.S_PUBLIC_IP }}:/opt/script/
         echo "Files copied successfully."
 
     # Run git-setup.sh on the VM
     - name: Run git-setup.sh on the VM
       run: |
         echo "Running git-setup.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/git-setup.sh || { echo "Script failed"; exit 1; }' 
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/git-setup.sh || { echo "Script failed"; exit 1; }' 
         echo "Script executed successfully."
 
     # Run lemp-setup.sh on the VM
     - name: Run lemp-setup.sh on the VM
       run: |
         echo "Running lemp-setup.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/lemp-setup.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/lemp-setup.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
     # Run cloudflare-dns.sh on the VM
     - name: Run cloudflare-dns.sh on the VM
       run: |
         echo "Running cloudflare-dns.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/cloudflare-dns.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/cloudflare-dns.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
     # Run wordpress-install.sh on the VM
     - name: Run wordpress-install.sh on the VM
       run: |
         echo "Running wordpress-install.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/wordpress-install.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/wordpress-install.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
 
     # Run certbot-ssl-install.sh on the VM
     - name: Run certbot-ssl-install.sh on the VM
       run: |
         echo "Running certbot-ssl-install.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/certbot-ssl-install.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
     
     # Run certbot-ssl-install.sh on the VM
     - name: Run certbot-ssl-install.sh on the VM
       run: |
         echo "Running certbot-ssl-install.sh on VM..."
-        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/mount.sh || { echo "Script failed"; exit 1; }'
+        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.S_PUBLIC_IP }} 'sudo bash /opt/script/EPA/mount.sh || { echo "Script failed"; exit 1; }'
         echo "Script executed successfully."
