comment automation from git-setup

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -85,21 +85,33 @@ jobs:
           cat ./lemp-setup.sh
 
           echo "Secrets to cloudflare-dns.sh"
-          sed -i 's/S_DOMAIN/${{ secrets.MY_ELASTIC_IP }}/g' ./cloudflare-dns.sh
-          sed -i 's/S_PUBLIC_IP/${{ secrets.CF_ZONE_ID }}/g' ./cloudflare-dns.sh
-          sed -i 's/S_CF_API/${{ secrets.EMAIL }}/g' ./cloudflare-dns.sh
-          sed -i 's/S_CF_ZONE_ID/${{ secrets.DOMAIN }}/g' ./cloudflare-dns.sh
+          sed -i 's/S_DOMAIN/${{ secrets.S_DOMAIN }}/g' ./cloudflare-dns.sh
+          sed -i 's/S_PUBLIC_IP/${{ secrets.S_PUBLIC_IP }}/g' ./cloudflare-dns.sh
+          sed -i 's/S_CF_API/${{ secrets.S_CF_API }}/g' ./cloudflare-dns.sh
+          sed -i 's/S_CF_ZONE_ID/${{ secrets.S_CF_ZONE_ID }}/g' ./cloudflare-dns.sh
           cat ./cloudflare-dns.sh
 
           echo "Secrets to wordpress-install.sh"
           cat ./wordpress-install.sh
 
           echo "Secrets to certbot-ssl-install.sh"
-          sed -i 's/S_DOMAIN/${{ secrets.S_DOMAIM }}/g' ./certbot-ssl-install.sh
+          sed -i 's/S_DOMAIN/${{ secrets.S_DOMAIN }}/g' ./certbot-ssl-install.sh
           sed -i 's/S_EMAIL/${{ secrets.S_EMAIL }}/g' ./certbot-ssl-install.sh
           cat ./certbot-ssl-install.sh
 
-          
+      - name: Copy files to VM
+        run: |
+          echo "Copying files to VM..."
+          scp -r -i private_key -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} "${PWD}/" ${{ secrets.SSH_USERNAME }}@${{ secrets.S_PUBLIC_IP }}:~
+          echo "Files copied successfully."
+            
+      - name: Run git-setup.sh on the VM
+        run: |
+          echo "Running git-setup.sh on VM..."
+          ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.ELASTIC_IP }} 'sudo bash /home/ubuntu/EPA-Wordpress-project/git-setup.sh || { echo "Script failed"; exit 1; }' 
+          echo "Script executed successfully."
+
+
           
 
         
